Repository googleinterns/step36-2020, pull requests merged in 2020-07, with the labels that each got.

#34 Fix Front-End to show Books Properly
  src/main/webapp/index.html
  src/main/webapp/styles/results.css
Labels: MVP

#35 Update footer and website name
  src/main/webapp/index.html
  src/main/webapp/templates/results.html
Labels: MVP

#40 Fix Books API Call
  src/main/java/com/google/sps/servlets/BooksServlet.java
Labels: MVP

#26 Implement Civic Servlet in frontend.
  src/main/java/com/google/sps/servlets/actions/CivicServlet.java
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
  src/main/webapp/scripts/civic.js
  src/main/webapp/scripts/results.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keywords.html
Labels: Alpha Launch, MVP

#30 Add UI for civic information.
  src/main/webapp/scripts/civic.js
  src/main/webapp/scripts/results.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/civic.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keywords.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, MVP

#33 Government officals frontend
  src/main/webapp/styles/profile.css
  src/main/webapp/templates/keywords.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, MVP

#25 Blob Integration
  pom.xml
  src/main/java/com/google/sps/data/Keywords.java
  src/main/java/com/google/sps/servlets/ImageServlet.java
  src/main/java/com/google/sps/servlets/KeywordServlet.java
  src/main/webapp/index.html
  src/main/webapp/scripts/keywords.js
Labels: Alpha Launch

#27 Implement location cookies
  src/main/webapp/index.html
  src/main/webapp/scripts/cookies.js
  src/main/webapp/scripts/index.js
Labels: Alpha Launch, MVP

#42 Fix font-sizes and proportions
  src/main/webapp/styles/base.css
  src/main/webapp/styles/civic.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/profile.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keyword.html
Labels: Alpha Launch

#46 Fix blobstore issue, re-enable button
  src/main/java/com/google/sps/data/Keywords.java
  src/main/java/com/google/sps/servlets/ImageServlet.java
  src/main/webapp/index.html
  src/main/webapp/scripts/keywords.js
Labels: MVP, cla: yes

#45 Merge all MVP branches
  src/main/java/com/google/sps/data/Keywords.java
  src/main/java/com/google/sps/data/UrlRequest.java
  src/main/java/com/google/sps/servlets/BooksServlet.java
  src/main/java/com/google/sps/servlets/ImageServlet.java
  src/main/java/com/google/sps/servlets/KeywordServlet.java
  src/main/webapp/index.html
  src/main/webapp/scripts/keywords.js
  src/main/webapp/scripts/results.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/loader.css
  src/main/webapp/templates/results.html
Labels: MVP, cla: yes

#41 Redesign results data pipeline.
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/base.css
  src/main/webapp/styles/civic.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/profile.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keyword.html
  src/main/webapp/templates/keywords.html
  src/main/webapp/templates/location.html
  src/main/webapp/templates/noKeywords.html
  src/main/webapp/templates/results.html
Labels: MVP

#50 Fix duplicate keywords
  src/main/java/com/google/sps/data/Keywords.java
Labels: MVP, cla: yes

#48 Re-instate keywords.js changes
  src/main/java/com/google/sps/data/Keywords.java
  src/main/webapp/scripts/keywords.js
Labels: MVP, bug, cla: yes

#51 Hotfix for MVP.
  src/main/webapp/index.html
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/civic.css
Labels: MVP, bug, cla: yes

#52 Update loading screen.
  src/main/webapp/scripts/results.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/base.css
Labels: Alpha Launch, cla: yes, enhancement

#53 Print Unicode characters in projects and books text
  src/main/java/com/google/sps/servlets/BooksServlet.java
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
Labels: Alpha Launch, bug, cla: yes

#59 Implement loading counter.
  src/main/webapp/scripts/counter.js
  src/main/webapp/scripts/results.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/templates/results.html
Labels: Alpha Launch, cla: yes, enhancement

#55 Make Maven Command Line Arguments for API Keys
  README.md
  pom.xml
  src/main/java/com/google/sps/data/GetAPIKeyUtil.java
  src/main/java/com/google/sps/servlets/BooksServlet.java
  src/main/java/com/google/sps/servlets/LocationServlet.java
  src/main/java/com/google/sps/servlets/actions/CivicServlet.java
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
  src/main/resources/project.properties
Labels: cla: yes

#64 Fix UI nits
  src/main/webapp/styles/location.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/location.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, bug, cla: yes

#63 Add back button
  src/main/webapp/scripts/results.js
  src/main/webapp/styles/back.css
  src/main/webapp/templates/results.html
Labels: MVP, cla: yes, enhancement

#62 Implement progress bar
  src/main/webapp/scripts/counter.js
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/progress.css
  src/main/webapp/templates/results.html
Labels: Alpha Launch, cla: yes, enhancement

#61 Add instructions
  src/main/webapp/index.html
  src/main/webapp/styles/index.css
Labels: cla: yes, enhancement

#60 Input nits
  src/main/java/com/google/sps/data/Keywords.java
  src/main/webapp/scripts/keywords.js
Labels: cla: yes

#65 Redesign keyword UI
  src/main/webapp/styles/active.css
  src/main/webapp/styles/dropdown.css
  src/main/webapp/styles/location.css
  src/main/webapp/styles/profile.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keyword.html
  src/main/webapp/templates/location.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, cla: yes, enhancement

#56 Use dynamic location
  src/main/java/com/google/sps/servlets/BooksServlet.java
  src/main/java/com/google/sps/servlets/LocationServlet.java
  src/main/java/com/google/sps/servlets/actions/CivicServlet.java
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
  src/main/webapp/index.html
  src/main/webapp/scripts/cookies.js
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/toggle.js
Labels: Alpha Launch, bug, cla: yes, enhancement

#67 Fix frontend nits.
  src/main/webapp/index.html
  src/main/webapp/scripts/counter.js
  src/main/webapp/scripts/keywords.js
  src/main/webapp/styles/active.css
  src/main/webapp/styles/base.css
  src/main/webapp/styles/dropdown.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/location.css
  src/main/webapp/styles/profile.css
  src/main/webapp/templates/keyword.html
  src/main/webapp/templates/location.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, bug, cla: yes, enhancement

#68 Implement loading in index.html
  src/main/webapp/index.html
  src/main/webapp/scripts/keywords.js
  src/main/webapp/styles/index.css
  src/main/webapp/templates/results.html
Labels: Alpha Launch, cla: yes, enhancement

#70 Add color scheme.
  src/main/webapp/scripts/toggle.js
  src/main/webapp/styles/active.css
  src/main/webapp/styles/base.css
  src/main/webapp/styles/dropdown.css
  src/main/webapp/styles/profile.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/keyword.html
Labels: Alpha Launch, cla: yes, enhancement

#66 Back End for News
  src/main/java/com/google/sps/data/Article.java
  src/main/java/com/google/sps/servlets/NewsServlet.java
Labels: cla: yes

#73 Implement complete responsive UI
  src/main/webapp/index.html
  src/main/webapp/scripts/counter.js
  src/main/webapp/scripts/index.js
  src/main/webapp/styles/active.css
  src/main/webapp/styles/back.css
  src/main/webapp/styles/base.css
  src/main/webapp/styles/dropdown.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/loader.css
  src/main/webapp/styles/location.css
  src/main/webapp/styles/profile.css
  src/main/webapp/styles/progress.css
  src/main/webapp/styles/results.css
Labels: Alpha Launch, bug, cla: yes, enhancement

#75 Added link to website in README
  README.md
Labels: cla: yes, documentation

#77 Working News Front End
  src/main/java/com/google/sps/servlets/NewsServlet.java
  src/main/webapp/scripts/toggle.js
  src/main/webapp/templates/keyword.html
Labels: cla: yes, enhancement

#71 Attempt text detection first before resorting to label detection
  src/main/java/com/google/sps/servlets/ImageServlet.java
Labels: cla: yes

#69 Implement Testing Framework for News Servlet
  pom.xml
  src/main/java/com/google/sps/data/Article.java
  src/main/java/com/google/sps/servlets/NewsServlet.java
  src/test/java/com/google/sps/data/emptyHTML.txt
  src/test/java/com/google/sps/data/fullNewsHTML.txt
  src/test/java/com/google/sps/data/partialNewsHTML.txt
  src/test/java/com/google/sps/tests/NewsTest.java
Labels: cla: yes, testing

#83 Handle Bad Addresses Elegantly
  src/main/java/com/google/sps/data/UrlRequest.java
  src/main/java/com/google/sps/servlets/actions/CivicServlet.java
  src/main/webapp/scripts/load.js
  src/main/webapp/scripts/toggle.js
Labels: cla: yes

#82 Fix-upload button
  src/main/webapp/scripts/keywords.js
Labels: Alpha Launch, bug, cla: yes

#72 Uses client's country code as param for news servlet.
  src/main/java/com/google/sps/servlets/LocationServlet.java
  src/main/java/com/google/sps/servlets/NewsServlet.java
Labels: Alpha Launch, cla: yes, enhancement

#78 Allow User to Enter Address Manually
  src/main/java/com/google/sps/data/UrlRequest.java
  src/main/webapp/index.html
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/toggle.js
Labels: cla: yes, enhancement

#85 Fixed errors from merge conflict.
  src/main/java/com/google/sps/data/UrlRequest.java
  src/main/java/com/google/sps/servlets/LocationServlet.java
  src/main/java/com/google/sps/servlets/NewsServlet.java
  src/test/java/com/google/sps/tests/NewsTest.java
Labels: bug, cla: yes

#87 Fix Unicode error for keywords.
  src/main/java/com/google/sps/servlets/KeywordServlet.java
  src/main/java/com/google/sps/servlets/LocationServlet.java
  src/main/java/com/google/sps/servlets/actions/CivicServlet.java
Labels: bug, cla: yes

#88 Fix Address Feature
  src/main/webapp/scripts/toggle.js
Labels: bug, cla: yes

#92 Add Modal window to choose keywords set
  src/main/webapp/index.html
  src/main/webapp/scripts/index.js
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/modalWindow.html
Labels: Alpha Launch, cla: yes, enhancement

#90 Delete hardcoded json files
  src/main/webapp/json/keywords.json
  src/main/webapp/json/news.json
Labels: cla: yes

#89 Implement functional user log-in with a basic front-end
  src/main/java/com/google/sps/data/Keywords.java
  src/main/java/com/google/sps/servlets/AllKeywordsServlet.java
  src/main/java/com/google/sps/servlets/ImageServlet.java
  src/main/java/com/google/sps/servlets/KeywordServlet.java
  src/main/java/com/google/sps/servlets/UserServlet.java
  src/main/webapp/index.html
  src/main/webapp/scripts/keywords.js
Labels: Alpha Launch, cla: yes

#93 Add image validation
  src/main/java/com/google/sps/servlets/ImageServlet.java
Labels: Alpha Launch, bug, cla: yes

#95 Uppercase keywords
  src/main/java/com/google/sps/data/Keywords.java
Labels: Alpha Launch, cla: yes

#96 Edit civic feature
  src/main/webapp/scripts/civic.js
Labels: Alpha Launch, cla: yes, enhancement

#98 Solve bug to upload image in dev server
  src/main/java/com/google/sps/servlets/ImageServlet.java
Labels: bug, cla: yes

#81 Tests for UrlRequest.java
  pom.xml
  src/main/java/com/google/sps/data/UrlRequest.java
  src/test/java/com/google/sps/tests/UrlRequestTest.java
Labels: cla: yes, testing

#99 Modal window integration
  src/main/webapp/index.html
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/keywords.js
  src/main/webapp/scripts/logButton.js
  src/main/webapp/scripts/modalMenu.js
  src/main/webapp/styles/base.css
  src/main/webapp/styles/menu.css
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/menu.html
  src/main/webapp/templates/modalWindow.html
  src/main/webapp/templates/results.html
Labels: Alpha Launch, cla: yes, enhancement

#103 Update Location Cookie System
  src/main/java/com/google/sps/servlets/NewsServlet.java
  src/main/webapp/scripts/cookies.js
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/toggle.js
Labels: Alpha Launch, cla: yes

#106 Fixed single-quote formatting for news.
  src/main/java/com/google/sps/servlets/NewsServlet.java
Labels: Alpha Launch, bug, cla: yes

#105 Results block
  src/main/webapp/scripts/toggle.js
  src/main/webapp/templates/results.html
Labels: Alpha Launch, bug, cla: yes

#102 Implement delete keywords sets
  src/main/java/com/google/sps/servlets/DeleteKeywordsServlet.java
  src/main/webapp/scripts/modalMenu.js
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/modalWindow.html
  src/test/java/com/google/sps/tests/DeleteKeywordsServletTest.java
Labels: Alpha Launch, cla: yes, enhancement, testing
