Repository googleinterns/step36-2020, pull requests merged in 2020-08, with the labels that each got.

#86 Tests for ProjectsServlet.java
  src/main/java/com/google/sps/servlets/actions/ProjectsServlet.java
  src/test/java/com/google/sps/tests/ProjectsServletTest.java
Labels: cla: yes, testing

#97 Tests for ResultsServlet.java
  src/main/java/com/google/sps/servlets/ResultsServlet.java
  src/main/resources/results.test
  src/test/java/com/google/sps/tests/ResultsServletTest.java
Labels: cla: yes, testing

#108 Fix final UI nits
  src/main/webapp/index.html
  src/main/webapp/scripts/cookies.js
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/logButton.js
  src/main/webapp/scripts/modalMenu.js
  src/main/webapp/styles/base.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/menu.css
  src/main/webapp/templates/results.html
Labels: Alpha Launch, bug, cla: yes, enhancement

#110 Fix tests for ResultsServlet
  src/test/java/com/google/sps/tests/ResultsServletTest.java
Labels: bug, cla: yes, testing

#111 Fix login race condition.
  src/main/webapp/index.html
  src/main/webapp/scripts/index.js
  src/main/webapp/scripts/keywordsForm.js
  src/main/webapp/scripts/login.js
  src/main/webapp/styles/index.css
  src/main/webapp/templates/inputForm.html
Labels: bug, cla: yes

#113 Fix loading bar when using location
  src/main/webapp/scripts/toggle.js
Labels: bug, cla: yes

#117 Fix font size in main page
  src/main/webapp/index.html
  src/main/webapp/scripts/modalMenu.js
  src/main/webapp/styles/base.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/menu.css
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/results.html
Labels: bug, cla: yes, enhancement

#109 Update Readme with non-Google URL
  README.md
Labels: cla: yes

#114 Fix logout button functionality on results page
  src/main/webapp/index.html
  src/main/webapp/scripts/login.js
  src/main/webapp/templates/results.html
Labels: bug, cla: yes

#112 Update README.md to include java 8 command
  README.md
Labels: cla: yes, documentation

#121 Fix index page loading
  src/main/webapp/scripts/login.js
Labels: cla: yes

#119 Implement login validation in backend for results page.
  src/main/java/com/google/sps/servlets/ResultsServlet.java
  src/main/resources/results.test
  src/main/resources/results403.test
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/results.html
  src/main/webapp/templates/results403.html
  src/test/java/com/google/sps/tests/ResultsServletTest.java
Labels: bug, cla: yes, enhancement

#120 Fix font size in main page
  src/main/webapp/index.html
  src/main/webapp/scripts/modalMenu.js
  src/main/webapp/styles/base.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/menu.css
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/templates/results.html
Labels: bug, cla: yes, enhancement

#116 Detect Language of Input
  src/main/java/com/google/sps/data/Keywords.java
  src/main/java/com/google/sps/servlets/KeywordServlet.java
  src/main/webapp/scripts/toggle.js
Labels: cla: yes

#122 Update project ID in pom.xml
  pom.xml
Labels: cla: yes

#124 Fix font size results page
  src/main/webapp/index.html
  src/main/webapp/scripts/results.js
  src/main/webapp/styles/active.css
  src/main/webapp/styles/base.css
  src/main/webapp/styles/dropdown.css
  src/main/webapp/styles/index.css
  src/main/webapp/styles/loader.css
  src/main/webapp/styles/location.css
  src/main/webapp/styles/menu.css
  src/main/webapp/styles/modalWindow.css
  src/main/webapp/styles/progress.css
  src/main/webapp/styles/results.css
  src/main/webapp/templates/results.html
Labels: cla: yes, enhancement
